/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'loan' : IDL.Null,
  'account' : IDL.Null,
});
export const Product = IDL.Record({
  'maxAmount' : IDL.Float64,
  'features' : IDL.Vec(IDL.Text),
  'minAmount' : IDL.Float64,
  'name' : IDL.Text,
  'interestRate' : IDL.Float64,
  'category' : ProductCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'applicant' : IDL.Principal,
  'productCategory' : ProductCategory,
  'name' : IDL.Text,
  'productName' : IDL.Text,
  'email' : IDL.Text,
  'requestedAmount' : IDL.Opt(IDL.Float64),
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'editProduct' : IDL.Func([Product], [], []),
  'getApplication' : IDL.Func([IDL.Nat], [Application], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'listMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Float64)],
      [IDL.Nat],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'loan' : IDL.Null,
    'account' : IDL.Null,
  });
  const Product = IDL.Record({
    'maxAmount' : IDL.Float64,
    'features' : IDL.Vec(IDL.Text),
    'minAmount' : IDL.Float64,
    'name' : IDL.Text,
    'interestRate' : IDL.Float64,
    'category' : ProductCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'applicant' : IDL.Principal,
    'productCategory' : ProductCategory,
    'name' : IDL.Text,
    'productName' : IDL.Text,
    'email' : IDL.Text,
    'requestedAmount' : IDL.Opt(IDL.Float64),
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'editProduct' : IDL.Func([Product], [], []),
    'getApplication' : IDL.Func([IDL.Nat], [Application], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'listMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Float64)],
        [IDL.Nat],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };